### ISSUE TITLE
ke?

### ISSUE THREAD

**Issue by nat-n** [ShaneKilkelly/manuel#1]
I propose that it would be useful if there were some way to list available functions, and they further more the name for such a task/command should be "ke?".

I'm not sure that there is currently a way to do this without establishing a convention for readable or parseable documentation in manuelfiles. 

What do you think?

**Comment by JuneKelly** [comment]
After much deliberation, I've decided that this is a great idea.
Added in commit: https://github.com/ShaneKilkelly/manuel/commit/944535dea20530375cc9bed187f22952b2049ffb
