### ISSUE TITLE
Add arguments in manuel taks?

### ISSUE THREAD

**Issue by bserem** [ShaneKilkelly/manuel#6]
Is it possible to run a manuel task with arguments?

Example:
I have function `sass`, and I'd like to run it with `manuel sass __SOME_ARGUMENT__` to choose between development CSS or minified CSS.
Calling manuel tasks with arguments from other tasks would also be nice.

I understand that one option is to create another manuel task, but I was wondering if I could do this with arguments.

Thanks

ps: I am trying to perfect this code, which when done would probably be a nice starting point for people that want to work manuel
```
# Sass Compile
function sass {
  echo "[$(timestamp)] Cleaning up dist folder."
  rm -rf dist/css/*.css
  rm -rf dist/css/*.map

  echo "[$(timestamp)] Compiling SASS."
  for f in $(find . -name '[^_]*.scss'); do
    name=$(basename $f)
    name=$(echo $name | cut -f 1 -d '.')
    sassc -t expanded -m -l $f dist/css/$name.css
    sassc -t compressed $f dist/css/$name.min.css
    echo "[$(timestamp)] $name.css is" `stat --printf="%s" dist/css/$name.css` "bytes."
    echo "[$(timestamp)] $name.min.css is" `stat --printf="%s" dist/css/$name.min.css` "bytes."
  done
}
```

**Comment by JuneKelly** [comment]
Hi,

Args should be available in the usual `$1`, `$2`, etc variables within the task function. For clarity, tasks are just bash functions, so all the documentation [here](https://www.gnu.org/software/bash/manual/html_node/Shell-Functions.html) applies :)

Anyway, here's an example:

```bash

# in manuelfile

function build {
  echo ">> I am building in $1 mode"
}

# in shell

$ manuel build 'test'
>> I am building in test mode
```

**Comment by bserem** [comment]
Cool, thanks!
